### ISSUE TITLE
Don't load your styles from code

### ISSUE THREAD

**Issue by luisrudge** [davidguttman/react-pivot#13]
This is related to #12.
Because of [this line](https://github.com/davidguttman/react-pivot/blob/master/index.jsx#L437), webpack loads your css even if `defaultStyles: false`. That forces me to override your default styles with `important`:

```css
.reactPivot {
  box-shadow: none !important;
  background: transparent !important;
}
.reactPivot-pageNumber {
  cursor: pointer !important;
  font-size: 20px;
}
```

I think you shouldn't include your styles by default. Just let the "consumer" import the css from their code.
